language: php

php:
    # We only specify one version so we only get one worker
    - 5.2
    - 5.3
    - 5.4

before_script:
    - phpize && ./configure && make && sudo make install
    - echo "extension=AOP.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`